AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  counter

Globals:
  Function:
    Timeout: 5

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        Api:
          Type: Api
          Properties:
            Path: /counter
            Method: POST
            # Auth:
            #   ApiKeyRequired: InvokeRole
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DB

  DB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloud-resume-challenge-counter
      AttributeDefinitions: 
        - AttributeName: "PK"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "PK"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST


Outputs:
  ApiUrl:
    Value:
      Fn::Sub:
      - https://${ServerlessRestApi}.execute-api.${Region}.amazonaws.com/Prod/counter/
      - Region:
          Ref: AWS::Region
        ServerlessRestApi:
          Ref: ServerlessRestApi
