name: Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request: # for testing purposes; remove before merge
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: aws s3 sync ./public/ ${{ secrets.S3_BUCKET_NAME }} --delete
